server:
  port: 3344

spring:
  application:
    name: springcloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangrongxiaoqi/springcloud-config.git
          username: 19852292965
          password: 414wangrong601
