server:
  port: 9527

#Eureka配置
eureka:
  client:
    register-with-eureka: false #是否向Eureka注册中心注册自己
    service-url: #监控页面
      defaultZone: http://eureka7001.com:7001/eureka/
      instance:
        instance-id: zuul9527.com #修改默认描述信息
        prefer-ip-address: true #显示ip地址

info:
  app.name: xiaoqi-springcloud
  company.name: xiaoqi

spring:
  application:
    name: springcloud-zuul

zuul:
  routes:
    mydept.serverId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*" #不能再使用这个路径访问了  *:隐藏全部的
  prefix: /wang #设置公共的前缀
